name: bcftools_view
description: Filter a VCF with bcftools view, with the filter expression supplied via ext.args; outputs a bgzipped VCF and tbi index
keywords:
  - filtering
  - VCF
  - variant calling
tools:
  - view:
      description: VCF/BCF conversion, view, subset and filter VCF/BCF files.
      homepage: http://samtools.github.io/bcftools/bcftools.html
      documentation: http://www.htslib.org/doc/bcftools.html
      tool_dev_url: https://github.com/samtools/bcftools
      doi: "10.1093/bioinformatics/btp352"
      licence: ["MIT"]
      identifier: biotools:bcftools
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information e.g. [ id:'test' ]
    - vcf:
        type: file
        description: Input VCF/BCF file to filter
        pattern: "*.{vcf.gz,vcf,bcf}"
    - tbi:
        type: file
        description: Tabix index of the input VCF
        pattern: "*.tbi"
output:
  vcf:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.vcf.gz":
          type: file
          description: Filtered VCF file
          pattern: "*.vcf.gz"
  tbi:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.tbi":
          type: file
          description: Tabix index of filtered VCF
          pattern: "*.tbi"
  versions_bcftools:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - bcftools:
          type: string
          description: The tool name
      - "bcftools --version | sed '1!d; s/^.*bcftools //'":
          type: string
          description: The command used to generate the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - bcftools:
          type: string
          description: The tool name
      - "bcftools --version | sed '1!d; s/^.*bcftools //'":
          type: string
          description: The command used to generate the version of the tool
authors:
  - "@robert-a-forsyth"
maintainers:
  - "@robert-a-forsyth"
